### ISSUE TITLE
pip install rst2db fails

### ISSUE THREAD

**Issue by getreu** [Abstrys/rst2db#5]
on my debian 8 with backports:

```
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/libxml2 -Isrc/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w

src/lxml/lxml.etree.c:83:20: fatal error: Python.h: No such file or directory

 #include "Python.h"

                    ^

compilation terminated.

Compile failed: command 'x86_64-linux-gnu-gcc' failed with exit status 1

creating tmp

cc -I/usr/include/libxml2 -I/usr/include/libxml2 -c /tmp/xmlXPathInitzpceyO.c -o tmp/xmlXPathInitzpceyO.o

cc tmp/xmlXPathInitzpceyO.o -lxml2 -o a.out

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
  Can't roll back lxml; was not uninstalled
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-23fbKQ/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-_NHlxT-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-23fbKQ/lxml
Storing debug log for failure in /root/.pip/pip.log
```

**Comment by EronHennessey** [comment]
Hi @getreu,

It looks like you're missing python development libraries on your system.

If you install python-dev (or python3-dev) first, it will probably resolve the problem.  Try:

```
sudo apt-get install python-dev python3-dev
```

and then try `setup.py install` again...

I've added a note about this to the [README](https://github.com/Abstrys/rst2db/blob/master/README.rst).

**Comment by getreu** [comment]
Thank you for your answer. I worked. I addition, I had to download the lastest master from Github and install this:

```
apt-get install zlib1g-dev
```

For most documents it works fine. Attached you will find a very simple template that fails.
[cheatsheet.pdf--Notes.rst.txt](https://github.com/Abstrys/rst2db/files/595700/cheatsheet.pdf--Notes.rst.txt)

## Error messanges

```
   NotImplementedError: abstrys.docutils_ext.docbook_writer.DocBookTranslator visiting unknown node type: decoration
```

Or

```
   abstrys.docutils_ext.docbook_writer: docinfo
  <docinfo><author>Getreu</author><date>2016-11-16</date><revision>1.0</revision><field><field_name>Description</field_name><field_body/></field></docinfo>
   NotImplementedError: abstrys.docutils_ext.docbook_writer.DocBookTranslator visiting unknown node type: author
```

**Comment by EronHennessey** [comment]
It's true, I haven't implemented all known node types... I freely accept help, however!

**Comment by getreu** [comment]
No problem. Thank you for your answer. Is there a list of (not) implemented node types?

**Comment by EronHennessey** [comment]
Thanks @getreu, I'll add a bit of code to report these at the end of a run. The current node types are handled in this file: https://github.com/Abstrys/rst2db/blob/master/abstrys/docutils_ext/docbook_writer.py

**Comment by getreu** [comment]
May I suggest not aborting with  NotImplementedError, but emitting a warning instead. Then standard documents can be processed, even if it is not perfect..
